// autoflex-vue/src/components/_ui/EntityListHeader/index.vue
<template>
  <div class="header">
    <div class="text-wrap">
      <h3>{{ title }}</h3>
      <small v-if="subtitle">{{ subtitle }}</small>
    </div>
    <Button
      :label="buttonLabel"
      icon="pi pi-plus"
      :data-testid="addButtonTestId"
      @click="$emit('add')"
    />
  </div>
</template>

<script setup lang="ts">
import Button from "primevue/button";

defineProps<{
  title: string;
  buttonLabel?: string;
  subtitle?: string;
  addButtonTestId?: string;
}>();

defineEmits<{
  add: [];
}>();
</script>

<style scoped>
.header {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 12px;
  gap: 8px;
}

.text-wrap {
  display: grid;
  gap: 2px;
}

h3 {
  margin: 0;
}

small {
  color: #6b7280;
}
</style>

// src/components/_ui/EntityListHeader/index.tsx
import { Button, Flex, Space, Typography } from 'antd';
import { PlusOutlined } from '@ant-design/icons';
import type { ReactNode } from 'react';

const { Title, Text } = Typography;

interface EntityListHeaderProps {
    title: string;
    subtitle: ReactNode;
    addLabel: string;
    onAdd: () => void;
    addButtonTestId?: string;
}

const EntityListHeader = ({ title, subtitle, addLabel, onAdd, addButtonTestId = 'add-button' }: EntityListHeaderProps) => (
    <Flex justify="space-between" align="center" wrap="wrap" gap={"8px"}>
        <Space direction="vertical" size={0}>
            <Title level={4} style={{ margin: 0 }}>
                {title}
            </Title>
            <Text type="secondary">{subtitle}</Text>
        </Space>
        <Button type="primary" icon={<PlusOutlined />} onClick={onAdd} data-testid={addButtonTestId}>
            {addLabel}
        </Button>
    </Flex>
);

export default EntityListHeader;
