// autoflex-vue/src/features/rawMaterials/components/RawMaterialsList/components/RawMaterialModal.vue
<template>
  <CrudModal
    :open="open"
    :title="editing ? 'Editar Insumo' : 'Novo Insumo'"
    :saving="saving"
    :width="'34rem'"
    @cancel="$emit('cancel')"
    @save="$emit('save')"
    @update:open="$emit('update:open', $event)"
  >
    <div class="form-grid">
      <div class="field">
        <label for="raw-name">Nome do Insumo</label>
        <InputText
          id="raw-name"
          v-model.trim="formData.name"
          data-testid="name-input"
          placeholder="Ex: Chapa de Aço 2mm"
          fluid
        />
      </div>

      <div class="field">
        <label for="raw-stock">Quantidade em Estoque</label>
        <input
          id="raw-stock"
          v-model.number="formData.stockQuantity"
          data-testid="stock-quantity-input"
          type="number"
          min="0"
          step="1"
          class="p-inputtext p-component"
        />
      </div>
    </div>
  </CrudModal>
</template>

<script setup lang="ts">
import InputText from "primevue/inputtext";
import { CrudModal } from "../../../../../components/_ui";

defineProps<{
  open: boolean;
  editing: boolean;
  saving: boolean;
  formData: {
    name: string;
    stockQuantity: number | null;
  };
}>();

defineEmits<{
  cancel: [];
  save: [];
  "update:open": [value: boolean];
}>();
</script>

<style scoped>
.form-grid {
  display: grid;
  gap: 12px;
}

.field {
  display: grid;
  gap: 6px;
}

input.p-inputtext {
  width: 100%;
}

label {
  font-size: 14px;
  font-weight: 500;
}
</style>

// src/features/rawMaterials/components/RawMaterialsList/components/RawMaterialModal/index.tsx
import { Form, Input, InputNumber } from "antd";
import type { FormInstance } from "antd";
import type { RawMaterial } from "../../../../types";
import type { FC } from "react";
import { CrudModal } from "../../../../../../components/_ui";

interface RawMaterialModalProps {
    open: boolean;
    editingRawMaterial: RawMaterial | null;
    form: FormInstance;
    onOk: () => void;
    onCancel: () => void;
}

const RawMaterialModal: FC<RawMaterialModalProps> = ({
    open,
    editingRawMaterial,
    form,
    onOk,
    onCancel,
}) => {
    return (
        <CrudModal
            open={open}
            editing={!!editingRawMaterial}
            entityName="Insumo"
            form={form}
            onOk={onOk}
            onCancel={onCancel}
            width={480}
        >
                <Form.Item
                    name="name"
                    label="Nome do Insumo"
                    rules={[{ required: true, message: "Informe o nome." }]}
                >
                    <Input placeholder="Ex: Chapa de Aço 2mm" data-testid="name-input" />
                </Form.Item>

                <Form.Item
                    name="stockQuantity"
                    label="Quantidade em Estoque"
                    rules={[
                        {
                            required: true,
                            message: "Informe a quantidade em estoque.",
                        },
                    ]}
                >
                    <InputNumber<number>
                        min={0}
                        step={1}
                        precision={0}
                        style={{ width: "100%" }}
                        placeholder="0"
                        data-testid="stock-quantity-input"
                    />
                </Form.Item>
        </CrudModal>
    );
};

export default RawMaterialModal;
