// autoflex-vue/src/layouts/MainLayout.vue
<template>
  <div class="layout-root">
    <aside class="sidebar desktop-only">
      <div class="logo">
        <i class="pi pi-cog" />
        <div>
          <h3>Autoflex</h3>
          <small>Gestão Industrial</small>
        </div>
      </div>

      <nav class="nav-list">
        <Button
          v-for="item in navItems"
          :key="item.key"
          :label="item.label"
          :icon="item.icon"
          :severity="activeView === item.key ? 'contrast' : undefined"
          text
          class="nav-btn"
          @click="navigateTo(item.key)"
        />
      </nav>
    </aside>

    <Sidebar v-model:visible="mobileSidebarOpen" position="left" class="mobile-sidebar">
      <template #header>
        <div class="logo mobile-logo">
          <i class="pi pi-cog" />
          <div>
            <h3>Autoflex</h3>
            <small>Gestão Industrial</small>
          </div>
        </div>
      </template>
      <nav class="nav-list">
        <Button
          v-for="item in navItems"
          :key="item.key"
          :label="item.label"
          :icon="item.icon"
          :severity="activeView === item.key ? 'contrast' : undefined"
          text
          class="nav-btn"
          @click="navigateTo(item.key, true)"
        />
      </nav>
    </Sidebar>

    <div class="content-area">
      <header class="topbar">
        <Button icon="pi pi-bars" text class="mobile-menu-btn" @click="mobileSidebarOpen = true" />
        <h2>{{ viewTitle }}</h2>
      </header>

      <main class="content">
        <RouterView />
      </main>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from "vue";
import { RouterView, useRoute, useRouter } from "vue-router";
import Sidebar from "primevue/sidebar";
import Button from "primevue/button";

type ActiveView = "products" | "rawMaterials" | "production";

const navItems: Array<{ key: ActiveView; label: string; icon: string }> = [
  { key: "products", label: "Produtos", icon: "pi pi-shopping-cart" },
  { key: "rawMaterials", label: "Insumos", icon: "pi pi-database" },
  { key: "production", label: "Simulador", icon: "pi pi-chart-bar" },
];

const viewTitles: Record<ActiveView, string> = {
  products: "Gestão de Produtos",
  rawMaterials: "Gestão de Insumos",
  production: "Simulador de Produção",
};

const route = useRoute();
const router = useRouter();
const mobileSidebarOpen = ref(false);

const activeView = computed<ActiveView>(() => {
  if (route.path.startsWith("/rawMaterials")) return "rawMaterials";
  if (route.path.startsWith("/production")) return "production";
  return "products";
});

const viewTitle = computed(() => viewTitles[activeView.value]);

const navigateTo = (key: ActiveView, closeMobile = false) => {
  void router.push(`/${key}`);
  if (closeMobile) {
    mobileSidebarOpen.value = false;
  }
};
</script>

<style scoped>
.layout-root {
  min-height: 100vh;
  display: grid;
  grid-template-columns: 220px 1fr;
}

.sidebar {
  background: #1e3a5f;
  color: #ffffff;
  border-right: 1px solid rgba(255, 255, 255, 0.08);
}

.logo {
  display: flex;
  align-items: center;
  gap: 10px;
  padding: 16px;
  border-bottom: 1px solid rgba(255, 255, 255, 0.08);
}

.logo i {
  color: #facc15;
  font-size: 20px;
}

.logo h3 {
  margin: 0;
  font-size: 16px;
}

.logo small {
  opacity: 0.7;
}

.nav-list {
  padding: 12px;
  display: grid;
  gap: 8px;
}

.nav-btn {
  justify-content: flex-start;
}

.content-area {
  display: grid;
  grid-template-rows: 56px 1fr;
  min-width: 0;
}

.topbar {
  background: #fff;
  border-bottom: 1px solid #e8edf3;
  display: flex;
  align-items: center;
  gap: 12px;
  padding: 0 16px;
  position: sticky;
  top: 0;
  z-index: 10;
}

.topbar h2 {
  margin: 0;
  font-size: 18px;
  font-weight: 600;
}

.content {
  padding: 16px;
}

.mobile-menu-btn {
  display: none;
}

@media (max-width: 768px) {
  .layout-root {
    grid-template-columns: 1fr;
  }

  .desktop-only {
    display: none;
  }

  .mobile-menu-btn {
    display: inline-flex;
  }

  .content {
    padding: 12px 8px;
  }
}
</style>

// src/layouts/MainLayout.tsx
import { useState } from "react";
import { Layout, Menu, Button, Drawer, Typography } from "antd";
import {
    DatabaseOutlined,
    ShoppingOutlined,
    BarChartOutlined,
    MenuOutlined,
    MenuFoldOutlined,
    MenuUnfoldOutlined,
    ExperimentOutlined,
} from "@ant-design/icons";
import { Outlet, useNavigate } from "react-router-dom";

const { Sider, Content, Header } = Layout;
const { Title, Text } = Typography;

type ActiveView = "products" | "rawMaterials" | "production";

const NAV_ITEMS = [
    { key: "products", icon: <ShoppingOutlined />, label: "Produtos" },
    { key: "rawMaterials", icon: <DatabaseOutlined />, label: "Insumos" },
    { key: "production", icon: <BarChartOutlined />, label: "Simulador" },
];

const VIEW_TITLES: Record<ActiveView, string> = {
    products: "Gestão de Produtos",
    rawMaterials: "Gestão de Insumos",
    production: "Simulador de Produção",
};

const SIDEBAR_BG = "#1e3a5f";

export default function Dashboard() {
    const [activeView, setActiveView] = useState<ActiveView>("products");
    const [siderCollapsed, setSiderCollapsed] = useState(false);
    const [drawerOpen, setDrawerOpen] = useState(false);

    const navigate = useNavigate();

    const menuEl = (isMobile = false) => (
        <Menu
            mode="inline"
            selectedKeys={[activeView]}
            items={NAV_ITEMS}
            theme="dark"
            inlineCollapsed={!isMobile && siderCollapsed}
            style={{ background: "transparent", border: "none" }}
            onClick={({ key }) => {
                setActiveView(key as ActiveView);
                if (isMobile) setDrawerOpen(false);
                navigate(`/${key}`);
            }}
        />
    );

    const logoEl = (collapsed = false) => (
        <Layout.Header
            style={{
                background: SIDEBAR_BG,
                height: 64,
                padding: "0 16px",
                display: "flex",
                alignItems: "center",
                gap: 12,
                borderBottom: "1px solid rgba(255,255,255,0.08)",
                lineHeight: "normal",
            }}
        >
            <ExperimentOutlined style={{ fontSize: 22, color: "#facc15" }} />
            {!collapsed && (
                <span>
                    <Title
                        level={5}
                        style={{ color: "#fff", margin: 0, lineHeight: 1.2 }}
                    >
                        Autoflex
                    </Title>
                    <Text
                        style={{ color: "rgba(255,255,255,0.5)", fontSize: 11 }}
                    >
                        Gestão Industrial
                    </Text>
                </span>
            )}
        </Layout.Header>
    );

    return (
        <Layout style={{ minHeight: "100vh" }}>
            {/* Desktop Sider */}
            <Sider
                collapsible
                collapsed={siderCollapsed}
                onCollapse={setSiderCollapsed}
                trigger={null}
                width={220}
                collapsedWidth={64}
                breakpoint="md"
                collapsedWidth={0}
                onBreakpoint={(broken) => setSiderCollapsed(broken)}
                style={{ background: SIDEBAR_BG }}
            >
                {logoEl(siderCollapsed)}
                {menuEl(false)}
            </Sider>

            {/* Mobile Drawer */}
            <Drawer
                open={drawerOpen}
                onClose={() => setDrawerOpen(false)}
                placement="left"
                size={220}
                styles={{
                    body: { padding: 0, background: SIDEBAR_BG },
                    header: { display: "none" },
                }}
            >
                {logoEl(false)}
                {menuEl(true)}
            </Drawer>

            <Layout>
                <Header
                    style={{
                        background: "#fff",
                        padding: "0 24px",
                        borderBottom: "1px solid #e8edf3",
                        display: "flex",
                        alignItems: "center",
                        justifyContent: "space-between",
                        position: "sticky",
                        top: 0,
                        zIndex: 10,
                        height: 56,
                        lineHeight: "56px",
                    }}
                >
                    {/* Left: toggle + title */}
                    <span
                        style={{
                            display: "flex",
                            alignItems: "center",
                            gap: 12,
                        }}
                    >
                        {/* Mobile hamburger */}
                        <Button
                            type="text"
                            icon={<MenuOutlined />}
                            onClick={() => setDrawerOpen(true)}
                            style={{ display: "none" }}
                            className="mobile-menu-btn"
                        />
                        {/* Desktop collapse */}
                        <Button
                            type="text"
                            icon={
                                siderCollapsed ? (
                                    <MenuUnfoldOutlined />
                                ) : (
                                    <MenuFoldOutlined />
                                )
                            }
                            onClick={() => setSiderCollapsed((v) => !v)}
                        />
                        <Title level={5} style={{ margin: 0 }}>
                            {VIEW_TITLES[activeView]}
                        </Title>
                    </span>
                </Header>

                <Content
                    style={{
                        background: "#f0f4f9",
                        padding: 24,
                        minHeight: "calc(100vh - 56px)",
                    }}
                >
                    <Outlet />
                </Content>
            </Layout>
        </Layout>
    );
}
